language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt update
  - sudo apt install gcc-6
  - sudo apt install g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushaj:$BINTRAY_API_KEY "https://api.bintray.com/content/andreyshah/Helloworld/Helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
